#      _____  _____   _____
#     |  __ \|  __ \ / ____|   /\
#     | |__) | |__) | |       /  \
#     |  _  /|  ___/| |      / /\ \
#     | | \ \| |    | |____ / ____ \
#     |_|  \_\_|     \_____/_/    \_\
#
#     Developer: tugg
#     Support: Contact me on discord @ tugg.
#
#     Current list of permissions:
#       1. rpca.reload - Permission node for the reload command
#       2. rpca.list - Permission node for the list command
#       3. Individual permissions for every action is below
#
#     The plugins messages use the MiniMessage formatting
#     Normal color codes won't work so keep that in mind
#
permission: '<bold><dark_gray>[<blue>RPCA<dark_gray>] <reset><white>You don''t have permission for this action!'
reload: '<bold><dark_gray>[<blue>RPCA<dark_gray>] <reset><white>You have reloaded the plugin!'
player: '<bold><dark_gray>[<blue>RPCA<dark_gray>] <reset><white>That player isn''t online!'
console: '<bold><dark_gray>[<blue>RPCA<dark_gray>] <reset><white>You can''t execute this command from console!'
action: '<bold><dark_gray>[<blue>RPCA<dark_gray>] <reset><white>This action doesn''t exist!'
list: '<bold><dark_gray>[<blue>RPCA<dark_gray>] <reset><white>The current list of actions is: <blue><actions>'
help:
  - ''
  - ' <blue><bold>RPCA'
  - ''
  - ' <green>[] <white>= optional arguments  <red><> <white>= required arguments'
  - ''
  - ' <white>/rpca reload <blue>- Reloads the configuration'
  - ' <white>/rpca list <blue>- Lists all the current actions'
  - ' <white>/rpca <red><action> <green>[player] <blue>- Use a chat action'
  - ''

actions:
  # The messages can either be a single string or a list of strings
  # If it's a list of string the plugin will select a random string
  # to be sent for that action
  kill: # Unique identifier used in the /rpca <action> command
    permission: rpca.kill # The permission node required inorder to execute the action command
    broadcast:
      enabled: true # Whether the action should be broadcast for everyone to see
      public: # You must use the <player1> & <player2> placeholders to refer to the player & player used in the argument
        - '<white><player1> has killed <player2>'
        - '<red><player1> has killed <player2>'
        - '<blue><player1> has killed <player2>'
      self: # From here you can only use the <player> placeholder to refer to the player
        - '<white><player> has killed themselves'
        - '<yellow><player> has killed themselves'
        - '<red><player> has killed themselves'
    message:
      self:
        - '<white>you have killed <player>'
        - '<light_purple>you have killed <player>'
        - '<red>you have killed <player>'
      target:
        - '<white><player> has killed you'
        - '<red><player> has killed you'
        - '<black><player> has killed you'
    self: # This gets sent if no player is put as a 2nd argument
      - '<white>you have killed yourself'
      - '<red>you have killed yourself'
      - '<yellow>you have killed yourself'