name: RoleplayChatActions
version: '${project.version}'
main: red.tugg.roleplaychatactions.RoleplayChatActions
api-version: '1.20'
load: POSTWORLD
authors: [tugg]
softdepend:
  - SuperVanish
  - CMI
commands:
  roleplaychatactions:
    aliases:
      - rpca
      - ca
    description: Command used to interact with the plugin.